version: '3.9'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=boainterdevcustomerdb
    volumes:
      - /data/mysql
  
  upload-app:
    image: upload-appv1
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
      - mysql
      
    ports:
      - 7074:7070
    volumes:
      - /data/compose-app